app:
  strategies:
    plan: true
    assessment: true
    aap-plan: true
    aap-san: true
  events:
    enabled: true

hmpps:
  sqs:
    provider: localstack
    localstackUrl: http://localstack:4566
