services:
  api:
    image: quay.io/hmpps/hmpps-assess-risks-and-needs-coordinator-api:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    ports:
      - "5005:5005"
    volumes:
      - ..:/app
      - ~/.gradle:/home/gradle/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: wiremock
      SP_API_BASE_URL: http://localhost:8089/sentence-plan
      SAN_API_BASE_URL: http://localhost:8089/strengths-and-needs
