---
# Per environment values which override defaults in hmpps-template-kotlin/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-coordinator-api-test.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    SAN_API_BASE_URL: "https://api.strengths-based-needs-test.hmpps.service.justice.gov.uk"
    SP_API_BASE_URL: "https://sentence-plan-api-test.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: 
