CREATE TABLE coordinator.oasys_version
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid        UUID UNIQUE                             NOT NULL,
    created_at  TIMESTAMPTZ                             NOT NULL,
    created_by  TEXT                                    NOT NUll,
    updated_at  TIMESTAMPTZ                             NOT NULL,
    version     BIGINT                                  NOT NULL,
    entity_uuid UUID                                    NOT NULL,
    CONSTRAINT pk_oasys_version PRIMARY KEY (id),
    CONSTRAINT uq_version_entity_uuid UNIQUE (version, entity_uuid)
);
